### ISSUE TITLE
Get tasks by status.

### ISSUE THREAD

**Issue by ahadahmed** [ahadahmed/task-manager#26]
Create an API to get all the tasks by status.

**Comment by mtwn105** [comment]
Hi @ahadahmed 

Can you explain this one so I can try it out?

**Comment by ahadahmed** [comment]
> Hi @ahadahmed
> 
> Can you explain this one so I can try it out?

Hi @mtwn105, This issue is about creating a new REST API in TaskController to get all the tasks by status. Currently, tasks have 3 possible states. 'OPEN', 'IN_PROGRESS', 'CLOSED'. While the REST endpoint will call with the specific status it will return the tasks with the corresponding status from DB.

**Comment by mtwn105** [comment]
Thanks, @ahadahmed.

I would like to work on this. You can assign to me.

**Comment by mtwn105** [comment]
Hi @ahadahmed 

Opened PR #32
